// Auto-generated from myPOS_UTP_Tariff_Table.xlsx — do not hand-edit numbers here.
// "percent" is the headline rate; "surchargePence" is an additional per-transaction
// pence surcharge shown on the source sheet as e.g. "1.15+0.01p".
import { MyposPackage } from "./types";

export const MYPOS_TARIFF_TABLE: MyposPackage[] = [
  {
    packageId: "UTP-UK-011-3p",
    cpConsumerDebit: {"percent":0.23},
    cpConsumerCredit: {"percent":0.5},
    cpPremiumConsumerCredit: {"percent":1.7},
    cpCommercialCredit: {"percent":1.7},
    cpCommercialDebit: {"percent":1.7},
    cpVisaBusinessDebit: {"percent":0.97},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-014-3p",
    cpConsumerDebit: {"percent":0.24},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.88},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.35},
    cnpCommercialCredit: {"percent":2.35},
    cnpCommercialDebit: {"percent":2.35},
    cnpVisaBusinessDebit: {"percent":2.35},
    vpay: {"percent":2.1},
    jcb: {"percent":2.35},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-015-3p",
    cpConsumerDebit: {"percent":0.24},
    cpConsumerCredit: {"percent":0.77},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.15,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.35},
    cnpCommercialCredit: {"percent":2.35},
    cnpCommercialDebit: {"percent":2.35,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.35,"surchargePence":0.01},
    vpay: {"percent":2.1},
    jcb: {"percent":2.35},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-027-3p",
    cpConsumerDebit: {"percent":0.25},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.78},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.35},
    cnpVisaBusinessDebit: {"percent":2.35},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.5},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-025-3p",
    cpConsumerDebit: {"percent":0.25},
    cpConsumerCredit: {"percent":0.62},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.97},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-020-3p",
    cpConsumerDebit: {"percent":0.25},
    cpConsumerCredit: {"percent":0.77},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.97},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-031-3p",
    cpConsumerDebit: {"percent":0.26},
    cpConsumerCredit: {"percent":0.66},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.91},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-035-3p",
    cpConsumerDebit: {"percent":0.27},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.82},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-044-3p",
    cpConsumerDebit: {"percent":0.28},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.92},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-041-3p",
    cpConsumerDebit: {"percent":0.28},
    cpConsumerCredit: {"percent":0.81},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.2,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.35},
    cnpCommercialCredit: {"percent":2.35},
    cnpCommercialDebit: {"percent":2.35,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.35,"surchargePence":0.01},
    vpay: {"percent":2.1},
    jcb: {"percent":2.35},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-046-3p",
    cpConsumerDebit: {"percent":0.3},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.89},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-049-3p",
    cpConsumerDebit: {"percent":0.3},
    cpConsumerCredit: {"percent":0.75},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.94},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: null,
    approvalGate: "Managers Approval",
  },
  {
    packageId: "UTP-UK-100-4p",
    cpConsumerDebit: {"percent":0.35},
    cpConsumerCredit: {"percent":0.75},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.04,
    atvRequirement: "£10 - £15",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-101-5p",
    cpConsumerDebit: {"percent":0.35},
    cpConsumerCredit: {"percent":0.75},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.05,
    atvRequirement: "£0 - £10",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-SIMT1-3p",
    cpConsumerDebit: {"percent":0.6},
    cpConsumerCredit: {"percent":0.6},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.8},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.1},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£150k+ THROUGHPUT/CTO",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-SIMT2-3p",
    cpConsumerDebit: {"percent":0.8},
    cpConsumerCredit: {"percent":0.8},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.8},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.1},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£100k-£150k THROUGHPUT/CTO",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-SIMT3-3p",
    cpConsumerDebit: {"percent":1},
    cpConsumerCredit: {"percent":1},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.8},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.1},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£50k-£100k THROUGHPUT/CTO",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-SIMT4-3p",
    cpConsumerDebit: {"percent":1.2},
    cpConsumerCredit: {"percent":1.2},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.8},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.1},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£0-£50k THROUGHPUT/CTO",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-SIMT6-3p",
    cpConsumerDebit: {"percent":0.5},
    cpConsumerCredit: {"percent":0.5},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.8},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.1},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£200k+ THROUGHPUT/CTO",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-055-3p",
    cpConsumerDebit: {"percent":0.32},
    cpConsumerCredit: {"percent":0.62},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-056-3p",
    cpConsumerDebit: {"percent":0.32},
    cpConsumerCredit: {"percent":0.82},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-066-3p",
    cpConsumerDebit: {"percent":0.34,"surchargePence":0.01},
    cpConsumerCredit: {"percent":1.06},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.21,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.4,"surchargePence":0.01},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-072-3p",
    cpConsumerDebit: {"percent":0.36,"surchargePence":0.01},
    cpConsumerCredit: {"percent":0.66},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.13,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.4,"surchargePence":0.01},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.5},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-074-3p",
    cpConsumerDebit: {"percent":0.36,"surchargePence":0.01},
    cpConsumerCredit: {"percent":0.89},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":1.13,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.4,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.4,"surchargePence":0.01},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-076-3p",
    cpConsumerDebit: {"percent":0.37},
    cpConsumerCredit: {"percent":0.91},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":1.05},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.5},
    cnpVisaBusinessDebit: {"percent":2.5},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-081-3p",
    cpConsumerDebit: {"percent":0.39},
    cpConsumerCredit: {"percent":0.69},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":0.95},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.55},
    cnpCommercialCredit: {"percent":2.55},
    cnpCommercialDebit: {"percent":2.55},
    cnpVisaBusinessDebit: {"percent":2.55},
    vpay: {"percent":2.25},
    jcb: {"percent":2.55},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-083-3p",
    cpConsumerDebit: {"percent":0.4},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.89},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-082-4p",
    cpConsumerDebit: {"percent":0.4},
    cpConsumerCredit: {"percent":0.8},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.89},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.04,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-086-3p",
    cpConsumerDebit: {"percent":0.43},
    cpConsumerCredit: {"percent":0.61},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.25},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.35},
    cnpCommercialCredit: {"percent":2.35},
    cnpCommercialDebit: {"percent":2.35},
    cnpVisaBusinessDebit: {"percent":2.35},
    vpay: {"percent":2.1},
    jcb: {"percent":2.35},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-090-3p",
    cpConsumerDebit: {"percent":0.45,"surchargePence":0.01},
    cpConsumerCredit: {"percent":0.81},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":1.32,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.5,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.5,"surchargePence":0.01},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-091-3p",
    cpConsumerDebit: {"percent":0.45},
    cpConsumerCredit: {"percent":0.97},
    cpPremiumConsumerCredit: {"percent":2.05},
    cpCommercialCredit: {"percent":2.05},
    cpCommercialDebit: {"percent":2.05},
    cpVisaBusinessDebit: {"percent":1.17},
    cnpConsumerDebit: {"percent":2.35},
    cnpConsumerCredit: {"percent":2.35},
    cnpPremiumConsumerCredit: {"percent":2.6},
    cnpCommercialCredit: {"percent":2.6},
    cnpCommercialDebit: {"percent":2.6},
    cnpVisaBusinessDebit: {"percent":2.6},
    vpay: {"percent":2.35},
    jcb: {"percent":2.6},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-092-3p",
    cpConsumerDebit: {"percent":0.46},
    cpConsumerCredit: {"percent":0.82},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":1.23},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.5},
    cnpVisaBusinessDebit: {"percent":2.5},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-093-3p",
    cpConsumerDebit: {"percent":0.47},
    cpConsumerCredit: {"percent":0.76},
    cpPremiumConsumerCredit: {"percent":2.05},
    cpCommercialCredit: {"percent":2.05},
    cpCommercialDebit: {"percent":2.05},
    cpVisaBusinessDebit: {"percent":1.12},
    cnpConsumerDebit: {"percent":2.35},
    cnpConsumerCredit: {"percent":2.35},
    cnpPremiumConsumerCredit: {"percent":2.6},
    cnpCommercialCredit: {"percent":2.6},
    cnpCommercialDebit: {"percent":2.6},
    cnpVisaBusinessDebit: {"percent":2.6},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-094-3p",
    cpConsumerDebit: {"percent":0.5},
    cpConsumerCredit: {"percent":1},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-097-3p",
    cpConsumerDebit: {"percent":0.58},
    cpConsumerCredit: {"percent":1.01},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.2},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-098-3p",
    cpConsumerDebit: {"percent":0.63},
    cpConsumerCredit: {"percent":0.91},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":2.45},
    cnpConsumerDebit: {"percent":2.4},
    cnpConsumerCredit: {"percent":2.4},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-099-3p",
    cpConsumerDebit: {"percent":0.66},
    cpConsumerCredit: {"percent":1.02},
    cpPremiumConsumerCredit: {"percent":2.15},
    cpCommercialCredit: {"percent":2.15},
    cpCommercialDebit: {"percent":2.15},
    cpVisaBusinessDebit: {"percent":1.43},
    cnpConsumerDebit: {"percent":2.45},
    cnpConsumerCredit: {"percent":2.45},
    cnpPremiumConsumerCredit: {"percent":2.7},
    cnpCommercialCredit: {"percent":2.7},
    cnpCommercialDebit: {"percent":2.7},
    cnpVisaBusinessDebit: {"percent":2.7},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-053-3p",
    cpConsumerDebit: {"percent":0.31},
    cpConsumerCredit: {"percent":0.63},
    cpPremiumConsumerCredit: {"percent":1.81},
    cpCommercialCredit: {"percent":1.81},
    cpCommercialDebit: {"percent":1.81},
    cpVisaBusinessDebit: {"percent":1.23,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.11},
    cnpConsumerCredit: {"percent":2.11},
    cnpPremiumConsumerCredit: {"percent":2.36},
    cnpCommercialCredit: {"percent":2.36},
    cnpCommercialDebit: {"percent":2.36},
    cnpVisaBusinessDebit: {"percent":2.36},
    vpay: {"percent":2.11},
    jcb: {"percent":2.36},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-051-3p",
    cpConsumerDebit: {"percent":0.31},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":0.92},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-054-3p",
    cpConsumerDebit: {"percent":0.32},
    cpConsumerCredit: {"percent":0.77},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.09},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-061-3p",
    cpConsumerDebit: {"percent":0.33},
    cpConsumerCredit: {"percent":0.57},
    cpPremiumConsumerCredit: {"percent":1.75},
    cpCommercialCredit: {"percent":1.75},
    cpCommercialDebit: {"percent":1.75},
    cpVisaBusinessDebit: {"percent":1.65},
    cnpConsumerDebit: {"percent":2.05},
    cnpConsumerCredit: {"percent":2.05},
    cnpPremiumConsumerCredit: {"percent":2.3},
    cnpCommercialCredit: {"percent":2.3},
    cnpCommercialDebit: {"percent":2.3},
    cnpVisaBusinessDebit: {"percent":2.3},
    vpay: {"percent":2.05},
    jcb: {"percent":2.3},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-063-3p",
    cpConsumerDebit: {"percent":0.33},
    cpConsumerCredit: {"percent":0.75},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":1},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.5},
    cnpVisaBusinessDebit: {"percent":2.5},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-064-3p",
    cpConsumerDebit: {"percent":0.33},
    cpConsumerCredit: {"percent":0.85},
    cpPremiumConsumerCredit: {"percent":1.95},
    cpCommercialCredit: {"percent":1.95},
    cpCommercialDebit: {"percent":1.95},
    cpVisaBusinessDebit: {"percent":0.9},
    cnpConsumerDebit: {"percent":2.25},
    cnpConsumerCredit: {"percent":2.25},
    cnpPremiumConsumerCredit: {"percent":2.5},
    cnpCommercialCredit: {"percent":2.5},
    cnpCommercialDebit: {"percent":2.5},
    cnpVisaBusinessDebit: {"percent":2.5},
    vpay: {"percent":2.25},
    jcb: {"percent":2.5},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£25+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-070-3p",
    cpConsumerDebit: {"percent":0.35},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":0.88},
    cnpConsumerDebit: {"percent":2.1},
    cnpConsumerCredit: {"percent":2.1},
    cnpPremiumConsumerCredit: {"percent":2.35},
    cnpCommercialCredit: {"percent":2.35},
    cnpCommercialDebit: {"percent":2.35},
    cnpVisaBusinessDebit: {"percent":2.35},
    vpay: {"percent":2.1},
    jcb: {"percent":2.35},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-071-3p",
    cpConsumerDebit: {"percent":0.36,"surchargePence":0.01},
    cpConsumerCredit: {"percent":0.56},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.23,"surchargePence":0.01},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4,"surchargePence":0.01},
    cnpVisaBusinessDebit: {"percent":2.4,"surchargePence":0.01},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-080-3p",
    cpConsumerDebit: {"percent":0.38},
    cpConsumerCredit: {"percent":1.11},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.25},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-085-3p",
    cpConsumerDebit: {"percent":0.43},
    cpConsumerCredit: {"percent":0.76},
    cpPremiumConsumerCredit: {"percent":1.8},
    cpCommercialCredit: {"percent":1.8},
    cpCommercialDebit: {"percent":1.8},
    cpVisaBusinessDebit: {"percent":1.25},
    cnpConsumerDebit: {"percent":2.15},
    cnpConsumerCredit: {"percent":2.15},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-095-3p",
    cpConsumerDebit: {"percent":0.53},
    cpConsumerCredit: {"percent":0.86},
    cpPremiumConsumerCredit: {"percent":1.85},
    cpCommercialCredit: {"percent":1.85},
    cpCommercialDebit: {"percent":1.85},
    cpVisaBusinessDebit: {"percent":1.15},
    cnpConsumerDebit: {"percent":2.35},
    cnpConsumerCredit: {"percent":2.35},
    cnpPremiumConsumerCredit: {"percent":2.4},
    cnpCommercialCredit: {"percent":2.4},
    cnpCommercialDebit: {"percent":2.4},
    cnpVisaBusinessDebit: {"percent":2.4},
    vpay: {"percent":2.15},
    jcb: {"percent":2.4},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.6},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
  {
    packageId: "UTP-UK-096-3p",
    cpConsumerDebit: {"percent":0.58},
    cpConsumerCredit: {"percent":0.91},
    cpPremiumConsumerCredit: {"percent":2.05},
    cpCommercialCredit: {"percent":2.05},
    cpCommercialDebit: {"percent":2.05},
    cpVisaBusinessDebit: {"percent":1.45},
    cnpConsumerDebit: {"percent":2.35},
    cnpConsumerCredit: {"percent":2.35},
    cnpPremiumConsumerCredit: {"percent":2.6},
    cnpCommercialCredit: {"percent":2.6},
    cnpCommercialDebit: {"percent":2.6},
    cnpVisaBusinessDebit: {"percent":2.6},
    vpay: {"percent":2.2},
    jcb: {"percent":2.6},
    cnpLevy: {"percent":0.2},
    premiumCnpLevy: {"percent":0.4},
    authFeeGBP: 0.03,
    atvRequirement: "£15+",
    approvalGate: null,
  },
];
